# Site settings
title: CS3300 Monsoon 2022
subtitle: Compiler Design
baseurl: "/cs3300_m22" # the subpath of your site, e.g. /blog/
url: "http://kayceesrk.github.io" # the base hostname & protocol for your site
syllabus: "http://www.cse.iitm.ac.in/course_details.php?arg=MTk="
githubdir: "kayceesrk/cs3300_m22"

# Author/user information
email: kcsrk@cse.iitm.ac.in
twitter_username: kc_srk
github_username:  kayceesrk
authorurl: "http://kcsrk.info"
address: |
    Department of Computer Science and Engineering
    SSB 401, Indian Institute of Technology, Madras
    Chennai, India 600036

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
